/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-06 19:17:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customer_002dreg_002dform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Registration Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"regi.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("  href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\"\r\n");
      out.write("  rel=\"stylesheet\"\r\n");
      out.write("/>\r\n");
      out.write("<link\r\n");
      out.write("  href=\"https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap\"\r\n");
      out.write("  rel=\"stylesheet\"\r\n");
      out.write("/>\r\n");
      out.write("<link\r\n");
      out.write("  href=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css\"\r\n");
      out.write("  rel=\"stylesheet\"\r\n");
      out.write("/>\r\n");
      out.write("<script\r\n");
      out.write("  type=\"text/javascript\"\r\n");
      out.write("  src=\"https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js\"\r\n");
      out.write("></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("	<form action=\"regi.jsp\">\r\n");
      out.write("\r\n");
      out.write("		<section class=\"h-100 bg-dark\">\r\n");
      out.write("			<div class=\"container py-5 h-100\">\r\n");
      out.write("				<div\r\n");
      out.write("					class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
      out.write("					<div class=\"col\">\r\n");
      out.write("						<div class=\"card card-registration my-4\">\r\n");
      out.write("							<div class=\"row g-0\">\r\n");
      out.write("								<div class=\"col-xl-6 d-none d-xl-block\">\r\n");
      out.write("									<img src=\"cargo1.jpg\" alt=\"Sample photo\" class=\"img-fluid h-100\" \r\n");
      out.write("										style=\"border-top-left-radius: 0.25rem; border-bottom-left-radius: 0.25rem;\" />\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-xl-6\">\r\n");
      out.write("									<div class=\"card-body p-md-5 text-black\">\r\n");
      out.write("										<h3 class=\"mb-5 text-uppercase\">customer registration\r\n");
      out.write("											form</h3>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"row\">\r\n");
      out.write("											<div class=\"col-md-6 mb-4\">\r\n");
      out.write("												<div class=\"form-outline\">\r\n");
      out.write("													<label class=\"form-label\" for=\"form3Example1m\">First\r\n");
      out.write("														name</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("														name=\"fname\" type=\"text\" id=\"form3Example1m\"\r\n");
      out.write("														class=\"form-control form-control-lg\" required\r\n");
      out.write("														placeholder=\"Enter First name\" />\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("											<div class=\"col-md-6 mb-4\">\r\n");
      out.write("												<div class=\"form-outline\">\r\n");
      out.write("													<label class=\"form-label\" for=\"form3Example1n\">Last\r\n");
      out.write("														name</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("														name=\"lname\" type=\"text\" id=\"form3Example1n\"\r\n");
      out.write("														class=\"form-control form-control-lg\" required\r\n");
      out.write("														placeholder=\"Enter Last name\" />\r\n");
      out.write("\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form-outline mb-4\">\r\n");
      out.write("											<label class=\"form-label\" for=\"form3Example8\">Permanent\r\n");
      out.write("												Address</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("												name=\"peraddress\" type=\"text\" id=\"form3Example8\"\r\n");
      out.write("												class=\"form-control form-control-lg\" required\r\n");
      out.write("												placeholder=\"Enter Permanent Address\" />\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form-outline mb-4\">\r\n");
      out.write("											<label class=\"form-label\" for=\"form3Example8\">Current\r\n");
      out.write("												Address</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("												name=\"curaddress\" type=\"text\" id=\"form3Example8\"\r\n");
      out.write("												class=\"form-control form-control-lg\" required\r\n");
      out.write("												placeholder=\"Enter Current Address\" />\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form-outline\">\r\n");
      out.write("											<label class=\"form-label\" for=\"MobileNumber\">Mobile\r\n");
      out.write("												Number</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("												name=\"mobileno\" type=\"tel\" id=\"phoneNumber\"\r\n");
      out.write("												class=\"form-control form-control-lg\" required\r\n");
      out.write("												placeholder=\"Enter Mobile Number\" />\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div\r\n");
      out.write("											class=\"d-md-flex justify-content-start align-items-center mb-4 py-2\">\r\n");
      out.write("\r\n");
      out.write("											<h6 class=\"mb-0 me-4\">Customer Type:</h6>\r\n");
      out.write("											<br></br>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"form-check form-check-inline mb-0 me-4\">\r\n");
      out.write("												<input name=\"custtype\" class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("													id=\"private\" value=\"option1\" /> <label\r\n");
      out.write("													class=\"form-check-label\" for=\"private\">Private</label>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("											<div class=\"form-check form-check-inline mb-0 me-4\">\r\n");
      out.write("												<input name=\"custtype\" class=\"form-check-input\" type=\"radio\"\r\n");
      out.write("													id=\"business\" value=\"option2\" /> <label\r\n");
      out.write("													class=\"form-check-label\" for=\"business\">Business</label>\r\n");
      out.write("											</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form-outline mb-4\">\r\n");
      out.write("											<label class=\"form-label\" for=\"form3Example97\">Email\r\n");
      out.write("												ID</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("												name=\"email\" type=\"text\" id=\"form3Example97\"\r\n");
      out.write("												class=\"form-control form-control-lg\" required\r\n");
      out.write("												placeholder=\"Enter Email ID\" />\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("										<div class=\"form-outline mb-4\">\r\n");
      out.write("											<label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\r\n");
      out.write("											<label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("												name=\"password\" type=\"password\" id=\"exampleInputPassword1\"\r\n");
      out.write("												class=\"form-control form-control-lg\" id=\"pswd1\"\r\n");
      out.write("												placeholder=\"Enter Password\" required>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"form-outline mb-4\">\r\n");
      out.write("											<label for=\"exampleInputPassword1\" class=\"form-label\">Confirm\r\n");
      out.write("												Password</label> <label style=\"color: red;\"><b>*</b></label> <input\r\n");
      out.write("												name=\"conpassword\" type=\"password\"\r\n");
      out.write("												id=\"exampleInputPassword1\"\r\n");
      out.write("												class=\"form-control form-control-lg\" id=\"pswd2\"\r\n");
      out.write("												placeholder=\"Enter Confirm Password\" required>\r\n");
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div class=\"d-flex justify-content-end pt-3\">\r\n");
      out.write("											<button type=\"Reset\" class=\"btn btn-light btn-lg\">Reset</button>\r\n");
      out.write("											<button type=\"submit\" class=\"btn btn-warning btn-lg ms-2\">Submit\r\n");
      out.write("												form</button>\r\n");
      out.write("										</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</section>\r\n");
      out.write("	</form>\r\n");
      out.write(" ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
