/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-06 19:24:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class customer_005freg_005fform_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar", Long.valueOf(1672657792675L));
    _jspx_dependants.put("jar:file:/D:/WJP_220940320119/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Cargo-Services-App/WEB-INF/lib/spring-webmvc-4.3.20.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1539572356000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction.release();
    _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody.release();
    _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Registration Form</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"regi.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_spr_005fform_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spr_005fform_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:form
    org.springframework.web.servlet.tags.form.FormTag _jspx_th_spr_005fform_005f0 = (org.springframework.web.servlet.tags.form.FormTag) _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction.get(org.springframework.web.servlet.tags.form.FormTag.class);
    boolean _jspx_th_spr_005fform_005f0_reused = false;
    try {
      _jspx_th_spr_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005fform_005f0.setParent(null);
      // /customer_reg_form.jsp(16,1) name = action type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fform_005f0.setAction("regi.jsp");
      // /customer_reg_form.jsp(16,1) name = method type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fform_005f0.setMethod("post");
      // /customer_reg_form.jsp(16,1) name = commandName type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005fform_005f0.setCommandName("customer");
      int[] _jspx_push_body_count_spr_005fform_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005fform_005f0 = _jspx_th_spr_005fform_005f0.doStartTag();
        if (_jspx_eval_spr_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("		<section class=\"h-100 bg-dark\">\r\n");
            out.write("			<div class=\"container py-5 h-100\">\r\n");
            out.write("				<div\r\n");
            out.write("					class=\"row d-flex justify-content-center align-items-center h-100\">\r\n");
            out.write("					<div class=\"col\">\r\n");
            out.write("						<div class=\"card card-registration my-4\">\r\n");
            out.write("							<div class=\"row g-0\">\r\n");
            out.write("								<div class=\"col-xl-6 d-none d-xl-block\">\r\n");
            out.write("									<img src=\"cargo1.jpg\" alt=\"Sample photo\" class=\"img-fluid h-100\" \r\n");
            out.write("										style=\"border-top-left-radius: 0.25rem; border-bottom-left-radius: 0.25rem;\" />\r\n");
            out.write("								</div>\r\n");
            out.write("								<div class=\"col-xl-6\">\r\n");
            out.write("									<div class=\"card-body p-md-5 text-black\">\r\n");
            out.write("										<h3 class=\"mb-5 text-uppercase\">customer registration\r\n");
            out.write("											form</h3>\r\n");
            out.write("\r\n");
            out.write("										<div class=\"row\">\r\n");
            out.write("											<div class=\"col-md-6 mb-4\">\r\n");
            out.write("												<div class=\"form-outline\">\r\n");
            out.write("													<label class=\"form-label\" for=\"form3Example1m\">First\r\n");
            out.write("														name</label> <label style=\"color: red;\"><b>*</b></label> \r\n");
            out.write("														");
            if (_jspx_meth_spr_005finput_005f0(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("												</div>\r\n");
            out.write("											</div>\r\n");
            out.write("											<div class=\"col-md-6 mb-4\">\r\n");
            out.write("												<div class=\"form-outline\">\r\n");
            out.write("													<label class=\"form-label\" for=\"form3Example1n\">Last\r\n");
            out.write("														name</label> <label style=\"color: red;\"><b>*</b></label> \r\n");
            out.write("														");
            if (_jspx_meth_spr_005finput_005f1(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("												</div>\r\n");
            out.write("											</div>\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("										<div class=\"form-outline mb-4\">\r\n");
            out.write("											<label class=\"form-label\" for=\"form3Example8\">Permanent\r\n");
            out.write("												Address</label> <label style=\"color: red;\"><b>*</b></label> \r\n");
            out.write("												");
            if (_jspx_meth_spr_005finput_005f2(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("										<div class=\"form-outline mb-4\">\r\n");
            out.write("											<label class=\"form-label\" for=\"form3Example8\">Current\r\n");
            out.write("												Address</label> <label style=\"color: red;\"><b>*</b></label> \r\n");
            out.write("												");
            if (_jspx_meth_spr_005finput_005f3(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("										<div class=\"form-outline\">\r\n");
            out.write("											<label class=\"form-label\" for=\"MobileNumber\">Mobile\r\n");
            out.write("												Number</label> <label style=\"color: red;\"><b>*</b></label> ");
            if (_jspx_meth_spr_005finput_005f4(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("										<div\r\n");
            out.write("											class=\"d-md-flex justify-content-start align-items-center mb-4 py-2\">\r\n");
            out.write("\r\n");
            out.write("											<h6 class=\"mb-0 me-4\">Customer Type:</h6>\r\n");
            out.write("											<br></br>\r\n");
            out.write("\r\n");
            out.write("											<div class=\"form-check form-check-inline mb-0 me-4\">\r\n");
            out.write("												");
            if (_jspx_meth_spr_005finput_005f5(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write(" <label\r\n");
            out.write("													class=\"form-check-label\" for=\"private\">Private</label>\r\n");
            out.write("											</div>\r\n");
            out.write("\r\n");
            out.write("											<div class=\"form-check form-check-inline mb-0 me-4\">\r\n");
            out.write("												");
            if (_jspx_meth_spr_005finput_005f6(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write(" <label\r\n");
            out.write("													class=\"form-check-label\" for=\"business\">Business</label>\r\n");
            out.write("											</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("										<div class=\"form-outline mb-4\">\r\n");
            out.write("											<label class=\"form-label\" for=\"form3Example97\">Email\r\n");
            out.write("												ID</label> <label style=\"color: red;\"><b>*</b></label> ");
            if (_jspx_meth_spr_005finput_005f7(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("										<div class=\"form-outline mb-4\">\r\n");
            out.write("											<label for=\"exampleInputPassword1\" class=\"form-label\">Password</label>\r\n");
            out.write("											<label style=\"color: red;\"><b>*</b></label> \r\n");
            out.write("											");
            if (_jspx_meth_spr_005finput_005f8(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("										<div class=\"form-outline mb-4\">\r\n");
            out.write("											<label for=\"exampleInputPassword1\" class=\"form-label\">Confirm\r\n");
            out.write("												Password</label> <label style=\"color: red;\"><b>*</b></label> \r\n");
            out.write("												");
            if (_jspx_meth_spr_005finput_005f9(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("										<div class=\"d-flex justify-content-end pt-3\">\r\n");
            out.write("											");
            if (_jspx_meth_spr_005fbutton_005f0(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("											");
            if (_jspx_meth_spr_005fbutton_005f1(_jspx_th_spr_005fform_005f0, _jspx_page_context, _jspx_push_body_count_spr_005fform_005f0))
              return true;
            out.write("\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("									</div>\r\n");
            out.write("								</div>\r\n");
            out.write("							</div>\r\n");
            out.write("						</div>\r\n");
            out.write("					</div>\r\n");
            out.write("				</div>\r\n");
            out.write("			</div>\r\n");
            out.write("		</section>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_spr_005fform_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spr_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005fform_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005fform_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005fform_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005fform_0026_005fmethod_005fcommandName_005faction.reuse(_jspx_th_spr_005fform_005f0);
      _jspx_th_spr_005fform_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fform_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005fform_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f0 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f0_reused = false;
    try {
      _jspx_th_spr_005finput_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(39,14) null
      _jspx_th_spr_005finput_005f0.setDynamicAttribute(null, "name", "fname");
      // /customer_reg_form.jsp(39,14) null
      _jspx_th_spr_005finput_005f0.setDynamicAttribute(null, "type", "text");
      // /customer_reg_form.jsp(39,14) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f0.setId("form3Example1m");
      // /customer_reg_form.jsp(39,14) null
      _jspx_th_spr_005finput_005f0.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(39,14) null
      _jspx_th_spr_005finput_005f0.setDynamicAttribute(null, "placeholder", "Enter First name");
      // /customer_reg_form.jsp(39,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f0.setPath("fname");
      int[] _jspx_push_body_count_spr_005finput_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f0 = _jspx_th_spr_005finput_005f0.doStartTag();
        if (_jspx_th_spr_005finput_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f0);
      _jspx_th_spr_005finput_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f1 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f1_reused = false;
    try {
      _jspx_th_spr_005finput_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(50,14) null
      _jspx_th_spr_005finput_005f1.setDynamicAttribute(null, "name", "lname");
      // /customer_reg_form.jsp(50,14) null
      _jspx_th_spr_005finput_005f1.setDynamicAttribute(null, "type", "text");
      // /customer_reg_form.jsp(50,14) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f1.setId("form3Example1n");
      // /customer_reg_form.jsp(50,14) null
      _jspx_th_spr_005finput_005f1.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(50,14) null
      _jspx_th_spr_005finput_005f1.setDynamicAttribute(null, "placeholder", "Enter Last name");
      // /customer_reg_form.jsp(50,14) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f1.setPath("lname");
      int[] _jspx_push_body_count_spr_005finput_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f1 = _jspx_th_spr_005finput_005f1.doStartTag();
        if (_jspx_th_spr_005finput_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f1);
      _jspx_th_spr_005finput_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f1, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f2 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f2_reused = false;
    try {
      _jspx_th_spr_005finput_005f2.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(63,12) null
      _jspx_th_spr_005finput_005f2.setDynamicAttribute(null, "name", "peraddress");
      // /customer_reg_form.jsp(63,12) null
      _jspx_th_spr_005finput_005f2.setDynamicAttribute(null, "type", "text");
      // /customer_reg_form.jsp(63,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f2.setId("form3Example8");
      // /customer_reg_form.jsp(63,12) null
      _jspx_th_spr_005finput_005f2.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(63,12) null
      _jspx_th_spr_005finput_005f2.setDynamicAttribute(null, "placeholder", "Enter Permanent Address");
      // /customer_reg_form.jsp(63,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f2.setPath("peraddress");
      int[] _jspx_push_body_count_spr_005finput_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f2 = _jspx_th_spr_005finput_005f2.doStartTag();
        if (_jspx_th_spr_005finput_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f2);
      _jspx_th_spr_005finput_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f2, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f3 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f3_reused = false;
    try {
      _jspx_th_spr_005finput_005f3.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(73,12) null
      _jspx_th_spr_005finput_005f3.setDynamicAttribute(null, "name", "curaddress");
      // /customer_reg_form.jsp(73,12) null
      _jspx_th_spr_005finput_005f3.setDynamicAttribute(null, "type", "text");
      // /customer_reg_form.jsp(73,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f3.setId("form3Example8");
      // /customer_reg_form.jsp(73,12) null
      _jspx_th_spr_005finput_005f3.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(73,12) null
      _jspx_th_spr_005finput_005f3.setDynamicAttribute(null, "placeholder", "Enter Current Address");
      // /customer_reg_form.jsp(73,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f3.setPath("curaddress");
      int[] _jspx_push_body_count_spr_005finput_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f3 = _jspx_th_spr_005finput_005f3.doStartTag();
        if (_jspx_th_spr_005finput_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f3);
      _jspx_th_spr_005finput_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f3, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f4 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f4_reused = false;
    try {
      _jspx_th_spr_005finput_005f4.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(82,71) null
      _jspx_th_spr_005finput_005f4.setDynamicAttribute(null, "name", "mobileno");
      // /customer_reg_form.jsp(82,71) null
      _jspx_th_spr_005finput_005f4.setDynamicAttribute(null, "type", "tel");
      // /customer_reg_form.jsp(82,71) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f4.setId("phoneNumber");
      // /customer_reg_form.jsp(82,71) null
      _jspx_th_spr_005finput_005f4.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(82,71) null
      _jspx_th_spr_005finput_005f4.setDynamicAttribute(null, "placeholder", "Enter Mobile Number");
      // /customer_reg_form.jsp(82,71) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f4.setPath("mobileno");
      int[] _jspx_push_body_count_spr_005finput_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f4 = _jspx_th_spr_005finput_005f4.doStartTag();
        if (_jspx_th_spr_005finput_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f4);
      _jspx_th_spr_005finput_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f4, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f5 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f5_reused = false;
    try {
      _jspx_th_spr_005finput_005f5.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(97,12) null
      _jspx_th_spr_005finput_005f5.setDynamicAttribute(null, "name", "custtype");
      // /customer_reg_form.jsp(97,12) null
      _jspx_th_spr_005finput_005f5.setDynamicAttribute(null, "class", "form-check-input");
      // /customer_reg_form.jsp(97,12) null
      _jspx_th_spr_005finput_005f5.setDynamicAttribute(null, "type", "radio");
      // /customer_reg_form.jsp(97,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f5.setId("private");
      // /customer_reg_form.jsp(97,12) null
      _jspx_th_spr_005finput_005f5.setDynamicAttribute(null, "value", "option1");
      // /customer_reg_form.jsp(97,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f5.setPath("custtype");
      int[] _jspx_push_body_count_spr_005finput_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f5 = _jspx_th_spr_005finput_005f5.doStartTag();
        if (_jspx_th_spr_005finput_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f5);
      _jspx_th_spr_005finput_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f5, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f6 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f6_reused = false;
    try {
      _jspx_th_spr_005finput_005f6.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(103,12) null
      _jspx_th_spr_005finput_005f6.setDynamicAttribute(null, "name", "custtype");
      // /customer_reg_form.jsp(103,12) null
      _jspx_th_spr_005finput_005f6.setDynamicAttribute(null, "class", "form-check-input");
      // /customer_reg_form.jsp(103,12) null
      _jspx_th_spr_005finput_005f6.setDynamicAttribute(null, "type", "radio");
      // /customer_reg_form.jsp(103,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f6.setId("business");
      // /customer_reg_form.jsp(103,12) null
      _jspx_th_spr_005finput_005f6.setDynamicAttribute(null, "value", "option2");
      // /customer_reg_form.jsp(103,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f6.setPath("custtype");
      int[] _jspx_push_body_count_spr_005finput_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f6 = _jspx_th_spr_005finput_005f6.doStartTag();
        if (_jspx_th_spr_005finput_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005fvalue_005ftype_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f6);
      _jspx_th_spr_005finput_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f6, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f7 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f7_reused = false;
    try {
      _jspx_th_spr_005finput_005f7.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(117,67) null
      _jspx_th_spr_005finput_005f7.setDynamicAttribute(null, "name", "email");
      // /customer_reg_form.jsp(117,67) null
      _jspx_th_spr_005finput_005f7.setDynamicAttribute(null, "type", "text");
      // /customer_reg_form.jsp(117,67) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f7.setId("form3Example97");
      // /customer_reg_form.jsp(117,67) null
      _jspx_th_spr_005finput_005f7.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(117,67) null
      _jspx_th_spr_005finput_005f7.setDynamicAttribute(null, "placeholder", "Enter Email ID");
      // /customer_reg_form.jsp(117,67) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f7.setPath("email");
      int[] _jspx_push_body_count_spr_005finput_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f7 = _jspx_th_spr_005finput_005f7.doStartTag();
        if (_jspx_th_spr_005finput_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f7);
      _jspx_th_spr_005finput_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f7, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f7_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f8(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f8 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f8_reused = false;
    try {
      _jspx_th_spr_005finput_005f8.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f8.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(127,11) null
      _jspx_th_spr_005finput_005f8.setDynamicAttribute(null, "name", "password");
      // /customer_reg_form.jsp(127,11) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f8.setPath("password");
      // /customer_reg_form.jsp(127,11) null
      _jspx_th_spr_005finput_005f8.setDynamicAttribute(null, "type", "password");
      // /customer_reg_form.jsp(127,11) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f8.setId("exampleInputPassword1");
      // /customer_reg_form.jsp(127,11) null
      _jspx_th_spr_005finput_005f8.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(127,11) null
      _jspx_th_spr_005finput_005f8.setDynamicAttribute(null, "placeholder", "Enter Password");
      int[] _jspx_push_body_count_spr_005finput_005f8 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f8 = _jspx_th_spr_005finput_005f8.doStartTag();
        if (_jspx_th_spr_005finput_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f8[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f8.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f8.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f8);
      _jspx_th_spr_005finput_005f8_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f8, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f8_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005finput_005f9(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:input
    org.springframework.web.servlet.tags.form.InputTag _jspx_th_spr_005finput_005f9 = (org.springframework.web.servlet.tags.form.InputTag) _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.get(org.springframework.web.servlet.tags.form.InputTag.class);
    boolean _jspx_th_spr_005finput_005f9_reused = false;
    try {
      _jspx_th_spr_005finput_005f9.setPageContext(_jspx_page_context);
      _jspx_th_spr_005finput_005f9.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(136,12) null
      _jspx_th_spr_005finput_005f9.setDynamicAttribute(null, "name", "conpassword");
      // /customer_reg_form.jsp(136,12) null
      _jspx_th_spr_005finput_005f9.setDynamicAttribute(null, "type", "password");
      // /customer_reg_form.jsp(136,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f9.setId("exampleInputPassword1");
      // /customer_reg_form.jsp(136,12) null
      _jspx_th_spr_005finput_005f9.setDynamicAttribute(null, "class", "form-control form-control-lg");
      // /customer_reg_form.jsp(136,12) null
      _jspx_th_spr_005finput_005f9.setDynamicAttribute(null, "placeholder", "Enter Confirm Password");
      // /customer_reg_form.jsp(136,12) name = path type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_spr_005finput_005f9.setPath("conpassword");
      int[] _jspx_push_body_count_spr_005finput_005f9 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005finput_005f9 = _jspx_th_spr_005finput_005f9.doStartTag();
        if (_jspx_th_spr_005finput_005f9.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005finput_005f9[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005finput_005f9.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005finput_005f9.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005finput_0026_005ftype_005fplaceholder_005fpath_005fname_005fid_005fclass_005fnobody.reuse(_jspx_th_spr_005finput_005f9);
      _jspx_th_spr_005finput_005f9_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005finput_005f9, _jsp_getInstanceManager(), _jspx_th_spr_005finput_005f9_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005fbutton_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:button
    org.springframework.web.servlet.tags.form.ButtonTag _jspx_th_spr_005fbutton_005f0 = (org.springframework.web.servlet.tags.form.ButtonTag) _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass.get(org.springframework.web.servlet.tags.form.ButtonTag.class);
    boolean _jspx_th_spr_005fbutton_005f0_reused = false;
    try {
      _jspx_th_spr_005fbutton_005f0.setPageContext(_jspx_page_context);
      _jspx_th_spr_005fbutton_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(147,11) null
      _jspx_th_spr_005fbutton_005f0.setDynamicAttribute(null, "type", "Reset");
      // /customer_reg_form.jsp(147,11) null
      _jspx_th_spr_005fbutton_005f0.setDynamicAttribute(null, "class", "btn btn-light btn-lg");
      int[] _jspx_push_body_count_spr_005fbutton_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005fbutton_005f0 = _jspx_th_spr_005fbutton_005f0.doStartTag();
        if (_jspx_eval_spr_005fbutton_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Reset");
            int evalDoAfterBody = _jspx_th_spr_005fbutton_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spr_005fbutton_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005fbutton_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005fbutton_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005fbutton_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass.reuse(_jspx_th_spr_005fbutton_005f0);
      _jspx_th_spr_005fbutton_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fbutton_005f0, _jsp_getInstanceManager(), _jspx_th_spr_005fbutton_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_spr_005fbutton_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_spr_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_spr_005fform_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spr:button
    org.springframework.web.servlet.tags.form.ButtonTag _jspx_th_spr_005fbutton_005f1 = (org.springframework.web.servlet.tags.form.ButtonTag) _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass.get(org.springframework.web.servlet.tags.form.ButtonTag.class);
    boolean _jspx_th_spr_005fbutton_005f1_reused = false;
    try {
      _jspx_th_spr_005fbutton_005f1.setPageContext(_jspx_page_context);
      _jspx_th_spr_005fbutton_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_spr_005fform_005f0);
      // /customer_reg_form.jsp(148,11) null
      _jspx_th_spr_005fbutton_005f1.setDynamicAttribute(null, "type", "submit");
      // /customer_reg_form.jsp(148,11) null
      _jspx_th_spr_005fbutton_005f1.setDynamicAttribute(null, "class", "btn btn-warning btn-lg ms-2");
      int[] _jspx_push_body_count_spr_005fbutton_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_spr_005fbutton_005f1 = _jspx_th_spr_005fbutton_005f1.doStartTag();
        if (_jspx_eval_spr_005fbutton_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("Submit\r\n");
            out.write("												form");
            int evalDoAfterBody = _jspx_th_spr_005fbutton_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_spr_005fbutton_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_spr_005fbutton_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_spr_005fbutton_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_spr_005fbutton_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fspr_005fbutton_0026_005ftype_005fclass.reuse(_jspx_th_spr_005fbutton_005f1);
      _jspx_th_spr_005fbutton_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_spr_005fbutton_005f1, _jsp_getInstanceManager(), _jspx_th_spr_005fbutton_005f1_reused);
    }
    return false;
  }
}
