/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2023-01-06 18:34:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-light\" style=\"background-color: #0005\">\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <button\r\n");
      out.write("      class=\"navbar-toggler\"\r\n");
      out.write("      type=\"button\"\r\n");
      out.write("      data-mdb-toggle=\"collapse\"\r\n");
      out.write("      data-mdb-target=\"#navbarSupportedContent\"\r\n");
      out.write("      aria-controls=\"navbarSupportedContent\"\r\n");
      out.write("      aria-expanded=\"false\"\r\n");
      out.write("      aria-label=\"Toggle navigation\"\r\n");
      out.write("    >\r\n");
      out.write("      <i class=\"fas fa-bars\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("      <a class=\"navbar-brand mt-2 mt-lg-0\" href=\"#\">\r\n");
      out.write("        <img\r\n");
      out.write("          src=\"https://dynamic.brandcrowd.com/preview/logodraft/018ff9c8-5db6-49ce-903a-93c8e08dceef/image/large.png\r\n");
      out.write("          \"\r\n");
      out.write("          height=\"60\"\r\n");
      out.write("          alt=\"MDB Logo\"\r\n");
      out.write("          loading=\"lazy\"\r\n");
      out.write("        />\r\n");
      out.write("      </a>\r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\" style=\"font-weight: 600\">\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"home.htm\">Home</a>\r\n");
      out.write("        </li>\r\n");
      out.write("         <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"product_add_form.htm\">Book Now</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"product_orders.htm\">Orders</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"contactus.htm\">Contact Us</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"aboutus.htm\">About Us</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"d-flex align-items-center\" style=\"font-weight: 600;\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"dropdown\" style= \"margin-right:20px;\">\r\n");
      out.write("        <a\r\n");
      out.write("          class=\"dropdown-toggle d-flex align-items-center hidden-arrow\"\r\n");
      out.write("          href=\"#\"\r\n");
      out.write("          id=\"navbarDropdownMenuAvatar\"\r\n");
      out.write("          role=\"button\"\r\n");
      out.write("          data-mdb-toggle=\"dropdown\"\r\n");
      out.write("          aria-expanded=\"false\"\r\n");
      out.write("          style=\"color: black;font-weight: 600\"\r\n");
      out.write("        >\r\n");
      out.write("      	Login\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul\r\n");
      out.write("          class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("          aria-labelledby=\"navbarDropdownMenuAvatar\"\r\n");
      out.write("        >\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"dropdown-item\" href=\"#\">Log in as Customer</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"dropdown-item\" href=\"Login.jsp\">Log in as Admin</a>\r\n");
      out.write("          </li>\r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"dropdown\" style= \"margin-right:20px\">\r\n");
      out.write("        <a\r\n");
      out.write("          class=\"dropdown-toggle d-flex align-items-center hidden-arrow\"\r\n");
      out.write("          href=\"#\"\r\n");
      out.write("          id=\"navbarDropdownMenuAvatar\"\r\n");
      out.write("          role=\"button\"\r\n");
      out.write("          data-mdb-toggle=\"dropdown\"\r\n");
      out.write("          aria-expanded=\"false\"\r\n");
      out.write("          style=\"color: black\"\r\n");
      out.write("        >\r\n");
      out.write("      	Signup\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul\r\n");
      out.write("          class=\"dropdown-menu dropdown-menu-end\"\r\n");
      out.write("          aria-labelledby=\"navbarDropdownMenuAvatar\"\r\n");
      out.write("        >\r\n");
      out.write("          <li>\r\n");
      out.write("            <a class=\"dropdown-item\" href=\"product_add_form.htm\">Signup as Customer</a>\r\n");
      out.write("          </li>\r\n");
      out.write("         \r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Right elements -->\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Container wrapper -->\r\n");
      out.write("</nav>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
